### PR TITLE
Bump golang.org/x/mod to latest

### PR DESCRIPTION
**Pull request by linux2647**
pacmod cannot parse Go modules that have a Go version declared with a patch version, which is supported in Go 1.21+.  The patch version is mandatory if a `toolchain` directive is not present.  This PR bumps golang.org/x/mod to its latest version, which can parse newer `go.mod` files.

### CODE REVIEW

**Comment by jpreese** [comment]
LGTM. Thanks ❤️

**Review by jpreese — APPROVED** [review]

**Comment by linux2647** [comment]
@jpreese Can you tag a new release?

**Comment by jpreese** [comment]
@linux2647 done!

**Comment by linux2647** [comment]
Thanks!

**Pull request merged**
